FILES_FOLDER = "files"
LOGS_FOLDER = "files/logs"
LOG_FILE_PATH = FILES_FOLDER + "/" + "log.txt"
SCHEDULE_PATH = FILES_FOLDER + "/" + "schedule.json"
BOT_CONFIG_PATH = FILES_FOLDER + "/" + "botconfig.json"
